// <auto-generated />
namespace computan.timesheet.Contexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class clientandprojectModify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(clientandprojectModify));
        
        string IMigrationMetadata.Id
        {
            get { return "201905090821294_clientandprojectModify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
