// <auto-generated />
namespace computan.timesheet.Contexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TimeEntryLogs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TimeEntryLogs));
        
        string IMigrationMetadata.Id
        {
            get { return "202105311309256_TimeEntryLogs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
