// <auto-generated />
namespace computan.timesheet.Contexts.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class orphanTickets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(orphanTickets));
        
        string IMigrationMetadata.Id
        {
            get { return "202203091037101_orphanTickets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
